### ISSUE TITLE
knowing id before deserializing with fixed type ?

### ISSUE THREAD

**Issue by Georges760** [DoumanAsh/json-rpc-types#12]
Is there a way to know the JSON-RPC id value before trying a deserialisation to a specific result type ?

using serde-json-core also ;)

In case of a JSON-RPC client implementation, before parsing a Result from server, it is usefull to know the id value to match it with a previously send Request with same id. So the Reponse result type may be chosen accordingly.

**Comment by Georges760** [comment]
i am currently trying by doing regex on the JSON data directly, but it would be nice if i could avoid regex dependencie.

**Comment by DoumanAsh** [comment]
Hm you could maybe create your own struct that only has `id` field?
deserializer will just skip all other fields:

```rust
#[serde(Deserialize)]
pub struct IdOnly {
    id: Id
}
```

This is a bit inefficient as you would have to parse response twice, but I don't think there is any other way.

Usually it is better to have fixed protocol for your results and describe it with all possible enumerations, but if it is not possible
