### ISSUE TITLE
some JSON-RPC Response implementation send both result and error but with one at null

### ISSUE THREAD

**Issue by Georges760** [DoumanAsh/json-rpc-types#9]
For instance [Stratum v1](https://braiins.com/stratum-v1/docs) is JSON-RPC v2 but Result look like :
```json
{"id": 10, "result": null, "error": [21, "Job not found", null]}
```
or
```json
{"error": null, "id": 4, "result": true}
```
In both case deserialize with current json-rpc-types return the Error `JSON-RPC Response contains both result and error field`.

The fact to combine these 2 JSON fields into a Rust Result is clever, but could we avoid the error above when one of the 2 is `null` in the JSON string ?

**Comment by DoumanAsh** [comment]
It owuld it is not actually correct JSON-RPC implementation.
While NULL value can qualify as non-existintence, spec clearly says that:

result
>This member MUST NOT exist if there was an error invoking the method.

error
>This member MUST NOT exist if there was no error triggered during invocation.

But I admit it is a bit inconvenient as you cannot trust some people to implement spec correctly so it should be easily changed to verify that it doesn't exist or at least NULL then.
I will check it

**Comment by Georges760** [comment]
Thx a lot, I tryed for 2 days messing with the `impl Deserialize for Response` but without success. That's why I came to ask help on this issue.

**Comment by DoumanAsh** [comment]
Sure no problem, but I would recommend to notify them if it is open source project or you can reach out to them.
It is buggy implementation of json rpc spec after all
